Am urmarit articulul [acesta](https://towardsdatascience.com/the-mathematics-behind-principal-component-analysis-fff2d7f4b643) legat de PCA

In [1]:
import numpy as np

In [3]:
m=np.array([[90, 90, 60, 60, 30],
            [60, 90, 60, 60, 30],
            [90, 30, 60, 90, 30]]).T

In [4]:
cm=np.cov(m.T)

In [5]:
vals,vects=np.linalg.eig(cm)

In [6]:
idx=vals.argsort()[::-1]
vals=vals[idx]
vects=vects[:,idx]

In [7]:
vals, vects

(array([1137.5874413 ,  786.38798335,   56.02457535]),
 array([[-0.65580225, -0.3859988 ,  0.6487899 ],
        [-0.4291978 , -0.51636642, -0.74104991],
        [-0.62105769,  0.7644414 , -0.17296443]]))

Alegem sa ignoram ultima coloana

In [9]:
vects=vects[:,:2:]
vals=vals[:2:]

In [10]:
vals, vects

(array([1137.5874413 ,  786.38798335]), array([[-0.65580225, -0.3859988 ],
        [-0.4291978 , -0.51636642],
        [-0.62105769,  0.7644414 ]]))

In [14]:
y=m.dot(vects)
y

array([[-140.6692628 ,    3.07784927],
       [-116.28173533,  -58.27962721],
       [-102.36346447,   -8.27542884],
       [-120.99519515,   14.65781313],
       [ -51.18173223,   -4.13771442]])

Asa am eliminat o dimensiune din maticea initiala pastrand cat mai multa informatie