Am urmarit articulul [acesta](https://towardsdatascience.com/the-mathematics-behind-principal-component-analysis-fff2d7f4b643) legat de PCA

In [1]:
import numpy as np

In [2]:
m=np.array([[90, 90, 60, 60, 30],
            [60, 90, 60, 60, 30],
            [90, 30, 60, 90, 30]]).T
m

array([[90, 60, 90],
       [90, 90, 30],
       [60, 60, 60],
       [60, 60, 90],
       [30, 30, 30]])

In [3]:
cm=np.cov(m.T)

In [4]:
vals,vects=np.linalg.eig(cm)

In [5]:
idx=vals.argsort()[::-1]
vals=vals[idx]
vects=vects[:,idx]

In [6]:
vals, vects

(array([1137.5874413 ,  786.38798335,   56.02457535]),
 array([[-0.65580225, -0.3859988 ,  0.6487899 ],
        [-0.4291978 , -0.51636642, -0.74104991],
        [-0.62105769,  0.7644414 , -0.17296443]]))

Alegem sa ignoram ultima coloana

In [7]:
vects=vects[:,:2:]
vals=vals[:2:]

In [8]:
vals, vects

(array([1137.5874413 ,  786.38798335]), array([[-0.65580225, -0.3859988 ],
        [-0.4291978 , -0.51636642],
        [-0.62105769,  0.7644414 ]]))

In [9]:
y=m.dot(vects)
y

array([[-140.6692628 ,    3.07784927],
       [-116.28173533,  -58.27962721],
       [-102.36346447,   -8.27542884],
       [-120.99519515,   14.65781313],
       [ -51.18173223,   -4.13771442]])

Asa am eliminat o dimensiune din maticea initiala pastrand cat mai multa informatie

Acum acelasi lucru doar ca normalizam vectorii din matrice cu $ z=\frac{x-\mu}{\sigma} $

In [10]:
mm=np.array([[m[:,i].mean() for i in range(m.shape[1])],
            [m[:,i].std() for i in range(m.shape[1])]])
mm

array([[66.        , 60.        , 60.        ],
       [22.44994432, 18.97366596, 26.83281573]])

In [11]:
m=np.array([(m[:,i]-mm[0][i])/mm[1][i] for i in range(m.shape[1])]).T

In [13]:
m

array([[ 1.06904497,  0.        ,  1.11803399],
       [ 1.06904497,  1.58113883, -1.11803399],
       [-0.26726124,  0.        ,  0.        ],
       [-0.26726124,  0.        ,  1.11803399],
       [-1.60356745, -1.58113883, -1.11803399]])

In [14]:
cm=np.cov(m.T)

In [15]:
vals,vects=np.linalg.eig(cm)

In [16]:
idx=vals.argsort()[::-1]
vals=vals[idx]
vects=vects[:,idx]

In [17]:
vals, vects

(array([2.37052682, 1.25      , 0.12947318]),
 array([[ 7.07106781e-01, -1.48620676e-16,  7.07106781e-01],
        [ 6.66666667e-01, -3.33333333e-01, -6.66666667e-01],
        [ 2.35702260e-01,  9.42809042e-01, -2.35702260e-01]]))

In [18]:
vects=vects[:,:2:]
vals=vals[:2:]

In [19]:
y=m.dot(vects)
y

array([[ 1.01945208e+00,  1.05409255e+00],
       [ 1.54649836e+00, -1.58113883e+00],
       [-1.88982237e-01,  3.97205465e-17],
       [ 7.45409018e-02,  1.05409255e+00],
       [-2.45150911e+00, -5.27046277e-01]])